name: Build & Push pyinstaller-alpine

on:
  # https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow
  workflow_dispatch: {}
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: https://github.com/pyinstaller/pyinstaller.git
          file: alpine.dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          tags: kinkard/pyinstaller-alpine:latest
